In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/content/Ecommerce_Order_Test_Dataset.csv')

In [3]:
display(df.head())

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Gender,City,Category,Product,Payment_Mode,Quantity,Unit_Price,Discount,Rating
0,ORD0001,01-01-2025,06-01-2025,Customer_058,Male,Mumbai,Clothing,Jacket,upi,5,1470.84,0.05,4.4
1,ORD0002,02-01-2025,05-01-2025,Customer_001,Male,Delhi,Books,Data Science Guide,Debit Card,3,2114.91,0.20,3.0
2,ORD0003,04-01-2025,06-01-2025,Customer_047,male,Mumbai,Electronics,Keyboard,Cash,3,3053.63,0.20,3.3
3,ORD0004,06-01-2025,09-01-2025,Customer_034,Female,Chennai,Clothing,Sneakers,Debit Card,2,1427.69,0.00,3.6
4,ORD0005,08-01-2025,15-01-2025,Customer_032,Female,Coimbatore,Clothing,Jeans,UPI,4,752.61,0.20,3.8

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       101 non-null    object
 1   Order_Date     101 non-null    object
 2   Delivery_Date  101 non-null    object
 3   Customer_Name  100 non-null    object
 4   Gender         101 non-null    object
 5   City           100 non-null    object
 6   Category       101 non-null    object
 7   Product        101 non-null    object
 8   Payment_Mode   100 non-null    object
 9   Quantity       101 non-null    int64
 10  Unit_Price     100 non-null    float64
 11  Discount       101 non-null    float64
 12  Rating         100 non-null    float64
dtypes: float64(3), int64(1), object(9)
memory usage: 10.4+ KB

In [5]:
df.describe()

         Quantity   Unit_Price    Discount      Rating
count  101.000000   100.000000  101.000000  100.000000
mean     3.168317  2579.265200    0.092079    3.738000
std      1.456498  1375.131202    0.070969    0.687813
min      1.000000   166.990000    0.000000    2.600000
25%      2.000000  1441.565000    0.050000    3.100000
50%      3.000000  2691.975000    0.100000    3.750000
75%      4.000000  3783.245000    0.150000    4.400000
max      5.000000  4927.900000    0.200000    5.000000

In [6]:
df.isnull()

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Gender,City,Category,Product,Payment_Mode,Quantity,Unit_Price,Discount,Rating
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,False,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False,False,False
100,False,False,False,False,False,False,False,False,False,False,False,False,False

In [7]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
96     False
97     False
98     False
99     False
100     True
Length: 101, dtype: bool

In [8]:
df.dtypes

Order_ID          object
Order_Date        object
Delivery_Date     object
Customer_Name     object
Gender            object
City              object
Category          object
Product           object
Payment_Mode      object
Quantity           int64
Unit_Price       float64
Discount         float64
Rating           float64
dtype: object

In [9]:
df['Gender'] = df['Gender'].str.capitalize()
display(df.head())

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Gender,City,Category,Product,Payment_Mode,Quantity,Unit_Price,Discount,Rating
0,ORD0001,01-01-2025,06-01-2025,Customer_058,Male,Mumbai,Clothing,Jacket,upi,5,1470.84,0.05,4.4
1,ORD0002,02-01-2025,05-01-2025,Customer_001,Male,Delhi,Books,Data Science Guide,Debit Card,3,2114.91,0.20,3.0
2,ORD0003,04-01-2025,06-01-2025,Customer_047,male,Mumbai,Electronics,Keyboard,Cash,3,3053.63,0.20,3.3
3,ORD0004,06-01-2025,09-01-2025,Customer_034,Female,Chennai,Clothing,Sneakers,Debit Card,2,1427.69,0.00,3.6
4,ORD0005,08-01-2025,15-01-2025,Customer_032,Female,Coimbatore,Clothing,Jeans,UPI,4,752.61,0.20,3.8